### ISSUE TITLE
Option "open window this window at application launch" stopped working.

### ISSUE THREAD

**Issue by vasileioskorompilias** [nhiroyasu/wallpaper-play#3]
Hello and congrats on your software which makes my desktop a lovely place :)
I think it is the only app that allows me to play YouTube. 

You have an option for not opening the window when the app starts (very handy), but it doesn't work. Not only that, but the window keeps popping up for some reason which is annoying.

I mainly play YouTube videos and some I have downloaded them to play offline when the internet is not reliable.

I run Ventura on a MacBookPro12,1

Thx

**Comment by nhiroyasu** [comment]
Thank you for using "wallpaper play" and reports app's bugs.

---

> You have an option for not opening the window when the app starts (very handy), but it doesn't work.

The bug was reproduced in my environment too. I would like to fix the bug at next patch version.

---

>  Not only that, but the window keeps popping up for some reason which is annoying.

Sorry, I was not able to reproduce this phenomenon. I'll try to search the cause.
If you'd like, upload the movie that occurring bugs and maybe I can figure out what's causing it.


Thank you :)
